services:
  database:
    container_name: database
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-net
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    image: backend
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
