services:
  database:
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
      - ./var/backend:/app/var/app
