"""add shop items and purchases

Revision ID: f7469d98a2d3
Revises: c47db805d03c
Create Date: 2026-04-23 13:21:07.702324

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7469d98a2d3"
down_revision: str | None = "c47db805d03c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_items",
        sa.Column(
            "category",
            sa.Enum("promo_code", "subscription", "bank_perk", name="shop_category"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("brand_name", sa.String(length=255), nullable=True),
        sa.Column("payload", sa.String(length=500), nullable=False),
        sa.Column("is_recommended", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shop_items_category"), "shop_items", ["category"], unique=False)
    op.create_index(
        "ix_shop_items_category_active", "shop_items", ["category", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_shop_items_is_recommended"), "shop_items", ["is_recommended"], unique=False
    )
    op.create_table(
        "purchases",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("shop_item_id", sa.UUID(), nullable=False),
        sa.Column("price_paid", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("payload_snapshot", sa.String(), nullable=False),
        sa.Column(
            "purchased_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["shop_item_id"], ["shop_items.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_purchases_user_id", "purchases", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_purchases_user_id", table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_shop_items_is_recommended"), table_name="shop_items")
    op.drop_index("ix_shop_items_category_active", table_name="shop_items")
    op.drop_index(op.f("ix_shop_items_category"), table_name="shop_items")
    op.drop_table("shop_items")
    # ### end Alembic commands ###
