"""add battlepass activations

Revision ID: c47db805d03c
Revises: a1b2c3d4e5f6
Create Date: 2026-04-23 01:59:38.626667

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c47db805d03c'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battlepass_activations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activated_date', sa.Date(), nullable=False),
    sa.Column(
        'activated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activated_date', name='uq_battlepass_activations_user_date')
    )
    op.create_index(
        'ix_battlepass_activations_user_date',
        'battlepass_activations',
        ['user_id', 'activated_date'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_battlepass_activations_user_date', table_name='battlepass_activations')
    op.drop_table('battlepass_activations')
    # ### end Alembic commands ###
